from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Protocol, runtime_checkable

from studio.domain.models import Booking, Charge, ClassSession, Member, NoShow

if TYPE_CHECKING:
    from studio.infrastructure.async_notifications import DispatchReport, Reminder


@runtime_checkable
class Clock(Protocol):
    def now(self) -> datetime: ...


@runtime_checkable
class MemberRepository(Protocol):
    def get(self, member_id: int) -> Member | None: ...
    def save(self, member: Member) -> Member: ...
    def list_all(self) -> list[Member]: ...


@runtime_checkable
class ClassRepository(Protocol):
    def get(self, class_id: int) -> ClassSession | None: ...
    def list_all(self, since: datetime | None = None) -> list[ClassSession]: ...


@runtime_checkable
class BookingRepository(Protocol):
    def get(self, booking_id: int) -> Booking | None: ...
    def add(self, booking: Booking) -> Booking: ...
    def save(self, booking: Booking) -> Booking: ...
    def for_class(self, class_id: int) -> list[Booking]: ...
    def for_member(self, member_id: int) -> list[Booking]: ...
    def no_shows_of(self, member_id: int) -> list[NoShow]: ...
    def record_no_show(self, no_show: NoShow) -> None: ...


@runtime_checkable
class PaymentGateway(Protocol):
    def charge(self, member: Member, amount_cents: int, concept: str) -> Charge: ...
    def refund(self, reference: str) -> bool: ...


@runtime_checkable
class Notifier(Protocol):
    def booking_confirmed(self, member: Member, session: ClassSession) -> None: ...
    def waitlisted(self, member: Member, session: ClassSession, position: int) -> None: ...
    def seat_released(self, member: Member, session: ClassSession) -> None: ...
    def booking_cancelled(self, member: Member, session: ClassSession, band: str) -> None: ...
    def member_blocked(self, member: Member, until: datetime) -> None: ...


@runtime_checkable
class ReminderSender(Protocol):
    async def send_all(self, reminders: list[Reminder]) -> DispatchReport: ...
